version: '3'

services:
    db:
        image: postgres
        environment:
                POSTGRES_PASSWORD: HollA@260504
                POSTGRES_DB: ubwebdb


    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
